name: Waka Readme

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    name: Update README with WakaTime stats
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Updated WakaTime stats